### PR TITLE
Revert PR 691 to fix compatibility with Safari and JavaFX

### LINKED ISSUE #752: [NAD] Voltage level legends not displayed properly
### Describe the current behavior

Since #691,
- the javafx component of [powsybl-dev-tools](https://github.com/powsybl/powsybl-dev-tools) is not displaying the voltage level legends properly
- safari browser neither (to be confirmed)

Image

### Describe the expected behavior

The voltage level legends are displayed properly

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by rolnico**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**
Fixes #752 

**What kind of change does this PR introduce?**
Reverts #691 

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

### CODE REVIEW

File: network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java [hunk 1]
```diff
@@ -813,20 +813,18 @@ private void drawHighlightedNode(XMLStreamWriter writer, VoltageLevelNode vlNode
...
-            for (Pair<VoltageLevelNode, TextNode> nodePair : textNodes) {
-                writeDetailedTextNode(writer, nodePair.getSecond(), nodePair.getFirst());
-            }
-            writer.writeEndElement();
-            writer.writeEndElement();
+        Collection<Pair<VoltageLevelNode, TextNode>> nodePairs = graph.getVoltageLevelTextPairs();
+        if (nodePairs.stream()
+            .noneMatch(nodePair -> nodePair.getSecond() != null)) {
+            // Do not write the section if there is no text node to display
+            return;
```
Comment (rolnico) [inline network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java]: I added this to avoid writing an empty section, but I don't know if it is necessary to keep it?
